version: "3.9"
services:
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    networks:
      - adoptation
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  data: {}

networks:
  adoptation:
    external: true

