version: "3.9"
services:
  db:
    image: library/postgres:13-alpine # название образа
    environment:
      POSTGRES_USER: server # имя пользователя для подключения
      POSTGRES_PASSWORD: password # пароль для подключения
      POSTGRES_DB: database # имя базы данных при первом запуске образа
    ports:
      - 6432:5432 # порт для подключения
    volumes:
      - data:/var/lib/postgresql/data # метка на образ диска для сохранения персистентности

volumes: # название папки для метки хранения данных
  data: {}