version: "3.9"
services:
  db:
    image: library/postgres:13-alpine # название образа
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: password
      POSTGRES_DB: adoptation
    networks:
      - adoptation
    ports:
      - 6432:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}

networks:
  adoptation: {}

